tap "dmarcotte/easy-move-plus-resize", "https://github.com/dmarcotte/easy-move-resize.git"
tap "felixkratz/borders", "git@github.com:FelixKratz/JankyBorders.git"
tap "felixkratz/formulae", "git@github.com:FelixKratz/JankyBorders.git"
tap "felixkratz/jankyborders", "git@github.com:FelixKratz/JankyBorders.git"
tap "felixkratz/tap", "git@github.com:FelixKratz/homebrew-formulae.git"
tap "homebrew/bundle"
tap "macos-fuse-t/cask", "https://github.com/macos-fuse-t/homebrew-cask.git"
tap "nikitabobko/tap"

brew "cowsay"
brew "felixkratz/tap/borders"
brew "glab"
brew "gradle"
brew "gromgit/fuse/s3fs-mac"
brew "hugo"
brew "llm"

cask "aerospace"
cask "easy-move+resize"
cask "fuse-t"
cask "hammerspoon"
cask "librewolf"
cask "macfuse"
